{
    "name": "Bramah Document Format",
    "summary": """Formatos de documentos para Bramah""",
    "version": "16.1.0.0",
    "description": """Formatos de documentos para Bramah""",
    "author": "Daniel Dominguez",
    "company": "Xtendoo",
    "website": "http://xtendoo.es",
    "category": "Extra Tools",
    "license": "AGPL-3",
    "depends": [
        "base",
        "stock",
        "stock_picking_report_valued",
        "account_invoice_report_grouped_by_picking",
    ],
    "data": [
        "views/invoice/invoice_document.xml",
        "views/sale_order/sale_order_document.xml",
        "views/layout/report_template.xml",
        "views/picking/stock_picking.xml",
    ],
    "installable": True,
    "auto_install": False,
}
